//good config for slow ocfs/notation system

{
    "aspectratio": 0.6666666666666666,
    "maxAllowedWidthFactor": 0.1,
    "panFenceOverlap": 0.1,
    "panSpeedBaseFactor": 0.5,
    "zoomSpeedBase": 10,
    "zoomDragFactor": 0.01,
    "wheelZoomIn": 1.5,
    "wheelZoomOut": 0.6666666666666666,
    "shiftMultiplier": 3,
    "ctrlMultiplier": 0.25,
    "ZoomIntoMouse": false,
    "modes": [
        1
    ],
    "LockScreen": false,
    "MathstickMode": true,
    "MathStick_UseLogarithmLength": false,
    "MathStick_LogarithmBase": 2,
    "DiagonalTickArrangement": false,
    "HarmonicInvtervalSpacing": true,
    "MultipleNotationOnSample": false,
    "EnableOrdinalFinder": false,
    "EnableSetViewPort": false,
    "SlowMode": false,
    "ZoomOutFencing": true,
    "PanOutFencing": true,
    "ShowHUD": true,
    "ShowLegends": false,
    "ShowTitle": true,
    "ShowFPS": true,
    "ShowDepthAdjustGui": true,
    "ShowOrdinalNotationConfigGui": true,
    "AlwaysShowDivisionOnIdle": false,
    "AlwaysShowDivisionOnInteraction": true,
    "ShowMiddleNumberLineDivision": false,
    "ShowTick": true,
    "ShowSample": true,
    "ShowLabel": true,
    "ShowTimelineLabel": true,
    "ShowCurrentPositionState": false,
    "ColorTick": false,
    "ColorSample": false,
    "ColorLabel": false,
    "ColorTimelineLabel": false,
    "BackgroundColor": "#ffffff",
    "DefaultTickColor": "#000000",
    "DefaultTimelineLabelColor": "#808080",
    "DefaultSampleColor": "#000000",
    "DefaultLabelColor": "#000000",
    "ScreenDivisionLineColor": "#ff0000",
    "FPSLabelColor": "#000000",
    "DepthAdjustGuiColor": "#000000",
    "TitleColor": "#000000",
    "AddNotationBtnColor": "#0098ff",
    "RemoveNotationBtnColor": "#ff4444",
    "SelectNotationBoxColor": "#000000",
    "MiddleNumberLineDivisionColor": "rgba(255,0,0,0.5)",
    "ZoomSelectionFillColor": "rgba(0, 150, 255, 0.2)",
    "ZoomSelectionBorder": "1px solid rgba(0, 150, 255, 0.8)",
    "RevertBtnColor": "#0098ff",
    "ConfigMenuBtnColor": "#000000",
    "CurrentPositionStateTextColor": "#ffffff",
    "TickSpacing": 5,
    "Tickheight": 0.0035,
    "TickWidth": 2,
    "TickAnchorPoint": 0.5,
    "labelscount": 8,
    "LabelBetweenTimelineSpacing": 30,
    "LabelBetweenTickSpacing": 5,
    "LabelBetweenLabelSpacing": 25,
    "TickBetweenLabelXoffest": 5,
    "fpsPrecision": 1,
    "MaxIntervalsDivision": -1,
    "MaxIntervalDepth": -1,
    "BigIntPrecisionMantissa": 6
}